const CHAT_ROLES = require('./chatRoles');
const P = require('./permissions');

module.exports = {
  [CHAT_ROLES.OWNER]: [
    // Groups
    P.GROUP_CREATE,
    P.GROUP_VIEW,
    P.GROUP_UPDATE,
    P.GROUP_DELETE,
    P.GROUP_ARCHIVE,
    P.GROUP_ADD_MEMBER,
    P.GROUP_REMOVE_MEMBER,

    // Messages
    P.MESSAGE_SEND,
    P.MESSAGE_VIEW,
    P.MESSAGE_UPDATE,
    P.MESSAGE_DELETE,

    // Conversations
    P.CONVERSATION_CREATE,
    P.CONVERSATION_VIEW,
    P.CONVERSATION_ARCHIVE,
    P.CONVERSATION_MANAGE_PARTICIPANTS,

    // System
    P.SYSTEM_VIEW_AUDIT_LOGS,
    P.SYSTEM_MANAGE_SETTINGS,
  ],

  [CHAT_ROLES.ADMIN]: [
    // Groups
    P.GROUP_CREATE,
    P.GROUP_VIEW,
    P.GROUP_UPDATE,
    P.GROUP_ADD_MEMBER,
    P.GROUP_REMOVE_MEMBER,

    // Messages
    P.MESSAGE_SEND,
    P.MESSAGE_VIEW,
    P.MESSAGE_UPDATE,
    P.MESSAGE_DELETE,

    // Conversations
    P.CONVERSATION_CREATE,
    P.CONVERSATION_VIEW,
    P.CONVERSATION_MANAGE_PARTICIPANTS,
  ],

  [CHAT_ROLES.MODERATOR]: [
    // Groups
    P.GROUP_VIEW,
    P.GROUP_ADD_MEMBER,

    // Messages
    P.MESSAGE_SEND,
    P.MESSAGE_VIEW,
    P.MESSAGE_UPDATE,
    P.MESSAGE_DELETE,
  ],

  [CHAT_ROLES.MEMBER]: [
    // Groups
    P.GROUP_VIEW,

    // Messages
    P.MESSAGE_SEND,
    P.MESSAGE_VIEW,
    P.MESSAGE_UPDATE,
  ],

  [CHAT_ROLES.VISITOR]: [
    // Read only
    P.GROUP_VIEW,
  ],
};
